# Generated by Django 5.1.6 on 2025-09-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectorreading',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectorreading',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
