# Generated by Django 5.1.6 on 2025-11-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_email_verified_user_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='detector_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
