# Generated by Django 5.1.6 on 2025-10-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectorreading',
            name='battery',
        ),
        migrations.AddField(
            model_name='detector',
            name='battery',
            field=models.IntegerField(default=100),
        ),
    ]
