# Generated by Django 5.1.6 on 2025-10-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_detectorreading_battery_detector_battery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detector',
            name='battery',
        ),
        migrations.AddField(
            model_name='detectorreading',
            name='battery',
            field=models.IntegerField(default=100),
        ),
    ]
