# Generated by Django 5.1.6 on 2025-10-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_detector_battery_detectorreading_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='detector',
            name='user_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detector',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detector',
            name='wifi_ssid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
