# Generated by Django 5.1.6 on 2025-10-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_detector_user_email_detector_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detector',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='detector',
            name='user_password',
        ),
        migrations.RemoveField(
            model_name='detector',
            name='wifi_password',
        ),
        migrations.RemoveField(
            model_name='detector',
            name='wifi_ssid',
        ),
    ]
